# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencyuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='transparencyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='transparencyuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='transparencyuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='transparencyuser',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='transparencyuser',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='transparencyuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
