# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180330_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transparencyuser',
            name='_id',
        ),
        migrations.AddField(
            model_name='transparencyuser',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
