# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180330_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transparencyuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transparencyuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
