# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180330_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransparencyApp',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransparencyApp')),
            ],
            options={
                'db_table': 'apps',
            },
        ),
    ]
