# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180416_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparencyapp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransparencyApp'),
        ),
    ]
