# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180416_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyapp',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
