# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transparencyapp_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transparencyapp',
            old_name='name',
            new_name='path_name',
        ),
    ]
