# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180417_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparencyapp',
            name='path_name',
            field=models.CharField(max_length=40),
        ),
    ]
