# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180417_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencyapp',
            options={'verbose_name': 'Transparency Application'},
        ),
        migrations.AlterModelTable(
            name='transparencyapp',
            table=None,
        ),
    ]
