# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180421_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencyuser',
            options={'verbose_name': 'Transparency Account'},
        ),
        migrations.RemoveField(
            model_name='transparencyapp',
            name='parent',
        ),
        migrations.AddField(
            model_name='transparencyapp',
            name='children',
            field=models.ManyToManyField(to='accounts.TransparencyApp'),
        ),
    ]
