# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180421_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyapp',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
