# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_transparencyapp_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transparencyapp',
            name='users',
        ),
    ]
