# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_transparencyapp_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyapp',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
