import sys
sys.dont_write_bytecode = True

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework import routers

from api import db
from api.apps import ApiConfig
from api.viewsets import ManagerViewSet, DatabaseQueryResultsViewSet, DatabaseViewSet

from rest_framework.routers import Route, DynamicDetailRoute, SimpleRouter

# This is DRF router for REST API ViewSets
router = routers.DefaultRouter()

# Register REST API endpoints with DRF Router
router.register(r'managers', ManagerViewSet, r"managers")
router.register(r'managers/(?P<search>.+)/', ManagerViewSet, r"search")
router.register(r'databases', DatabaseViewSet, r"databases")
router.register(r'query', DatabaseQueryResultsViewSet, r"query")

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    # REST API Root View Generated by DRF Router
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api/managers/(?P<search>.+)/', include(router.urls)),
    url(r'^api/managers/(?P<id>.+)/', include(router.urls)),
    url(r'^api/databases/(?P<id>.+)/', include(router.urls)),

    url(r'^api/query/(?P<sql>.+)/$',  include(router.urls)),
    url(r'^api/query/showTop5/(?P<id>.+)/$',  include(router.urls)),

    url(r'^', TemplateView.as_view(template_name="index.html")),
]

ApiConfig.startup()