export const ManagerTypes = {
    LOAD_MANAGER_SUCCESS : 'LOAD_MANAGER_SUCCESS',
    LOAD_MANAGERS_SUCCESS : 'LOAD_MANAGERS_SUCCESS',
    SEARCH_MANAGER_SUCCESS : 'SEARCH_MANAGER_SUCCESS',
    SELECT_MANAGER_SUCCESS : 'SELECT_MANAGER_SUCCESS',
    CLEAR_MANAGERS : 'CLEAR_MANAGERS',
    SEARCH_MANAGER : 'SEARCH_MANAGER',
    GET_MANAGER : 'GET_MANAGER',
    GET_MANAGERS : 'GET_MANAGERS',
    GET_RETURNS : 'GET_RETURNS',
    UPDATE_MANAGER_RETURNS : 'UPDATE_MANAGER_RETURNS',
    REMOVE_MANAGER : 'REMOVE_MANAGER',
} 

export const DatabaseTypes = {
    LOAD_DATABASES_SUCCESS : 'LOAD_DATABASES_SUCCESS',
    LOAD_DATABASES_ERROR : 'LOAD_DATABASES_ERROR',
    RUN_QUERY_SUCCESS : 'RUN_QUERY_SUCCESS',
    RUN_QUERY_ERROR : 'RUN_QUERY_ERROR'
}

export const ManagerListTypes = {
    GET_MANAGER_LIST : 'GET_MANAGER_LIST',
    SAVE_MANAGER_LIST_SUCCESS : 'SAVE_MANAGER_LIST_SUCCESS',
    SAVE_MANAGER_LIST_ERROR : 'SAVE_MANAGER_LIST_ERROR',
    LOAD_MANAGER_LIST_SUCCESS : 'LOAD_MANAGER_LIST_SUCCESS',
    LOAD_MANAGER_LISTS_SUCCESS : 'LOAD_MANAGER_LISTS_SUCCESS',

    CLEAR_MANAGER_LISTS : 'CLEAR_MANAGER_LISTS',
    ADD_MANAGER_LIST : 'ADD_MANAGER_LIST'
} 

export const HttpTypes = {
    HTTP_REQUEST : 'HTTP_REQUEST',
}
